apiVersion: apps/v1
kind: Deployment
metadata:
  name: danypooh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: danypooh
  template:
    metadata:
      labels:
        app: danypooh
    spec:
      containers:
      - image: okteto.dev/danypooh:latest
        name: danypooh
        envFrom:
        - configMapRef:
            name: danypooh-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: danypooh
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "danypooh"
    port: 8080
  selector:
    app: danypooh
